# Generated by Django 3.2.6 on 2021-10-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_auto_20211030_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200),
        ),
    ]
