# Generated by Django 3.2.6 on 2021-10-31 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientapp', '0002_auto_20211030_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ActingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ManyToManyField(to='bedapp.Acting')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_num', models.IntegerField()),
                ('bed_act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bedapp.actingset')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientapp.patient')),
            ],
        ),
    ]
