# Generated by Django 3.2.6 on 2021-10-31 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_alter_patient_slug'),
        ('bedapp', '0003_alter_acting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bedapp.actingset'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_num',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bed',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientapp.patient'),
        ),
    ]
